name: Add runbook in comment
on:
  issues:
    types:
      - labeled
jobs:
  add_runbook:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          pwd
          ls -al
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
            // console.log(context.issue);
            // const _issue = await github.rest.issues.get({
            //   issue_number: context.issue.number,
            //   owner: context.repo.owner,
            //   repo: context.repo.repo,
            // });
            // console.log(JSON.stringify({issue: _issue}, null, 2));
            // console.log(JSON.stringify({labels:_issue.data.labels}));
            // console.log(_issue.data.body);

            const { parseData, hasLabel, parseIssueTemplate, buildFieldLabelToIdMap } = require(`./dist/index.js`);
            const issueTemplate = parseIssueTemplate("bug-report.yaml");
            console.log(JSON.stringify(issueTemplate, null, 2));
            const issueFields = buildFieldLabelToIdMap(issueTemplate);
            console.log(JSON.stringify({issueFields}, null, 2));

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for reporting! ${_issue.data.title}`
            });
