name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          pwd
          ls -al
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.issue);
            const _issue = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(_issue);
            console.log(_issue.data.body);
            const script = require(`./dist/index.js`);
            console.log(script);
            script();
